language: node_js
node_js:
  - "0.10"
matrix:
  include:
    - node_js: "0.10"
      env: UNDERSCORE=1.4.4 MAINRUN=false
    - node_js: "0.10"
      env: UNDERSCORE=1.5 MAINRUN=false
    - node_js: "0.10"
      env: UNDERSCORE=1.6 MAINRUN=false
env: MAINRUN=true
before_install:
  - npm config set ca ""
install:
  - npm install
  # Which matrix settings -- otherwise default
  - if [[ $MAINRUN == false ]]; then npm install underscore@$UNDERSCORE; fi
script: if [[ $MAINRUN == true ]]; then gulp coverage; fi
after_success:
  - if [[ $MAINRUN == true ]]; then npm install -g codeclimate-test-reporter; fi
  - if [[ $MAINRUN == true ]]; then codeclimate < coverage/lcov.info; fi
